pypi:
  - armoriq-sdk

npm:
  - "@armoriq/sdk"
  - armoriq-openclaw-plugin
  - "@armoriq/armorclaw"

github:
  repos:
    - armoriq/armorclaw
    - armoriq/armoriq-sdk-customer
    - armoriq/conmap

discord:
  - 1450796662334423135
